import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Product } from 'src/app/Modals/Product';

@Component({
  selector: 'product-items',
  templateUrl: './product-items.component.html',
  styleUrls: ['./product-items.component.css']
})
export class ProductItemsComponent {
  @Input() searchText: string = '';
  @Output() productSelected = new EventEmitter<Product>();

  selectedFilterRadioButton: string = 'all';
  products =[
    {
    id: 1,
    name: "Nike React Infinity Run Flyknit",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "NIKE",
gender: "MEN",
category: "RUNNING", 
size: [6, 7, 8, 9, 10],
color: ["white", "Blue", "Black"],
price: 1299,
discountPrice : 899,
is_in_inventory: true,
items_left: 6,
imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSL7v5qwkXDHAkzLm7cra136dR7EnADq1Nqdg&s", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 2,
    name: "Adidas Stylish Shoes",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "ADIDAS",
gender: "MEN",
category: "CASUAL", 
size: [7,8, 9, 10],
color: ["Pink", "White", "Black"],
discountPrice : 1099,
price: 1499,
is_in_inventory: false,
items_left: 0,
imageURL: "https://img.tatacliq.com/images/i18//437Wx649H/MP000000022902708_437Wx649H_202407131602401.jpeg", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 3,
    name: "Puma Mens Sneakers",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "PUMA",
gender: "MEN",
category: "CASUAL", 
size: [6, 7, 8, 9],
color: ["Gray", "White", "Black"],
price: 999,
discountPrice : 769,
is_in_inventory: true,
items_left: 4,
imageURL: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_300,h_300/global/394371/03/sv01/fnd/IND/fmt/png/Smashic-Comfort-Casual-Sneakers", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 4,
    name: "Puma Stylish Sneaker",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "PUMA",
gender: "MEN",
category: "RUNNING", 
size: [6, 7, 8, 9, 10,11],
color: ["Yellow", "Olive", "Black"],
price: 1699,
discountPrice : 1299,
is_in_inventory: true,
items_left: 8,
imageURL: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_300,h_300/global/395111/04/sv01/fnd/IND/fmt/png/Smashic-Women's-Comfort-Casual-Sneakers", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 5,
    name: "Adidas Gym Wear",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "ADIDAS",
gender: "MEN",
category: "GYM", 
size: [40, 42, 44, 46, 48],
color: ["white", "Gray", "Black"],
price: 1249,
discountPrice : 899,
is_in_inventory: true,
items_left: 6,
imageURL: "https://soneesports.com/cdn/shop/products/IM2528_3_APPAREL_On_Model_Standard_View_white.jpg?v=1706465337", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 6,
    name: "Puma College Bag",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "PUMA",
gender: "MEN",
category: "COLLEGE", 
size: [20, 25, 30, 40],
color: ["white", "Olive", "Black"],
price: 899,
discountPrice : 659,
is_in_inventory: false,
items_left: 0,
imageURL: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/079392/03/fnd/IND/fmt/png/School-Backpack", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 7,
    name: "Adidas Casual Tshirt",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "ADIDAS",
gender: "MEN",
category: "CASUAL", 
size: [40, 42, 44, 46],
color: ["white", "Red", "Black"],
price: 1899,
discountPrice : 1399,
is_in_inventory: false,
items_left: 0,
imageURL: "https://soneesports.com/cdn/shop/products/IM4747_3_APPAREL_On_Model_Standard_View_white.jpg?v=1706465404", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 8,
    name: "Puma Sports Wear",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "PUMA",
gender: "MEN",
category: "EXERCISES", 
size: [6, 7, 8, 9, 10],
color: ["white", "Blue", "Red"],
price: 1199,
discountPrice : 899,
is_in_inventory: true,
items_left: 8,
imageURL: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_300,h_300/global/108127/02/sv01/fnd/IND/fmt/png/Badminton-Smash-Sprint-Indoor-Sports-Shoes", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 9,
    name: "Nike Party Wear",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "NIKE",
gender: "MEN",
category: "PARTY", 
size: [6, 7, 8, 9, 10,11],
color: ["Orange", "Green", "Black"],
price: 1499,
discountPrice : 1259,
is_in_inventory: true,
items_left: 6,
imageURL: "https://extrabutterny.in/cdn/shop/files/AURORA_HQ4988-030_PHSLH000-2000.jpg?v=1731659652", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 10,
    name: "Puma Girls Stylish Bag",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "PUMA",
gender: "GIRLS",
category: "COLLEGE", 
size: [20, 25, 30, 40],
color: ["white", "Pink", "Black"],
price: 859,
discountPrice : 629,
is_in_inventory: false,
items_left: 0,
imageURL: "https://pumageorgia.ge/uploads/md/jpg/110/07994333.jpg?v=1744359097", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 11,
    name: "Adidas React Party Wear",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "ADIDAS",
gender: "MEN",
category: "PARTY", 
size: [6, 7, 8, 9, 10],
color: ["Red", "Olive", "Black"],
price: 1029,
discountPrice : 759,
is_in_inventory: true,
items_left: 3,
imageURL: "https://cdn-images.farfetch-contents.com/20/33/17/17/20331717_50365594_1000.jpg", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 12,
    name: "Puma Air Max",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "PUMA",
gender: "MEN",
category: "RUNNING", 
size: [6, 7, 8, 9, 10],
color: ["Green", "Blue", "Black"],
price: 1039,
discountPrice : 869,
is_in_inventory: false,
items_left: 3,
imageURL: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/396463/22/sv01/fnd/IND/fmt/png/Palermo-Sneakers", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 13,
    name: "Wrogn Girls Slippers ",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "WROGN",
gender: "WOMEN",
category: "CASUAL", 
size: [40, 42, 44, 46],
color: ["white", "Gray", "Random"],
price: 1949,
discountPrice : 1299,
is_in_inventory: true,
items_left: 3,
imageURL: "https://m.media-amazon.com/images/I/71RoZBlx7vL._UY1000_.jpg", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 14,
    name: "Men's Adidas Precision",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "ADIDAS",
gender: "MEN",
category: "CASUAL", 
size: [6, 7, 8, 9, 10],
color: ["white", "Blue", "Black"],
price: 1499,
discountPrice : 959,
is_in_inventory: false,
items_left: 0,
imageURL: "https://img.tatacliq.com/images/i22//437Wx649H/MP000000025623006_437Wx649H_202503090456561.jpeg", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 15,
    name: "Bata Womens Slides",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "BATA",
gender: "WOMEN",
category: "SLIDES", 
size: [6, 7, 8, 9, 10],
color: ["Orange", "Green", "Black"],
price: 769,
discountPrice : 599,
is_in_inventory: true,
items_left: 3,
imageURL: "https://m.media-amazon.com/images/I/61VnGU4rkBL.jpg", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 16,
    name: "Womens Hand Bag",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "FREEPIK",
gender: "WOMEN",
category: "CASUAL", 
size: [10, 15, 20],
color: ["white", "Blue", "Black"],
price: 1299,
discountPrice : 899,
is_in_inventory: true,
items_left: 6,
imageURL: "https://img.freepik.com/free-photo/beautiful-elegance-luxury-fashion-green-handbag_1203-7655.jpg?semt=ais_hybrid&w=740", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 17,
    name: "Wenger Trolly Bag",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "WENGER",
gender: "MEN",
category: "CASUAL", 
size: [40, 50, 60, 70],
color: ["Pink", "White", "Black"],
discountPrice : 1099,
price: 1499,
is_in_inventory: false,
items_left: 0,
imageURL: "https://gutereise.in/cdn/shop/files/612763_1.jpg?v=1684304589", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 18,
    name: "Men's Fastrack Watches",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "FASTRACK",
gender: "MEN",
category: "CASUAL", 
size: [6, 7, 8, 9],
color: ["Gray", "White", "Black"],
price: 999,
discountPrice : 769,
is_in_inventory: true,
items_left: 4,
imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_JN3-LrhPxO4XTDzScDyOoMKRvgyGrGSiWA&s", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 19,
    name: "Puma Stylish Sneaker",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "PUMA",
gender: "MEN",
category: "RUNNING", 
size: [6, 7, 8, 9, 10,11],
color: ["Yellow", "Olive", "Black"],
price: 1699,
discountPrice : 1299,
is_in_inventory: true,
items_left: 8,
imageURL: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_300,h_300/global/395111/04/sv01/fnd/IND/fmt/png/Smashic-Women's-Comfort-Casual-Sneakers", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 20,
    name: "Amalfi Silver Watch",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "AMALFI",
gender: "WOMEN",
category: "CASUAL", 
size: [40, 42, 44, 46, 48],
color: ["white", "Gray", "Black"],
price: 1249,
discountPrice : 899,
is_in_inventory: true,
items_left: 6,
imageURL: "https://justcavalliwatches.com/wp-content/uploads/2023/10/JC1L270M0015-3.webp", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 21,
    name: "Puma Travel Bag",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "PUMA",
gender: "MEN",
category: "TRAVEL", 
size: [20, 25, 30, 40],
color: ["white", "Olive", "Black"],
price: 899,
discountPrice : 659,
is_in_inventory: false,
items_left: 0,
imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNSvEj5fXXKE5iNIlpjdK7DbQ4oyxkcE4PzQ&s", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 22,
    name: "Mens Fashon Jeans",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "LEVIS",
gender: "MEN",
category: "CASUAL", 
size: [30, 32, 34, 36],
color: ["white", "Red", "Black"],
price: 899,
discountPrice : 1099,
is_in_inventory: false,
items_left: 0,
imageURL: "https://levis.co.nz/cdn/shop/files/levis-mens-555-relaxed-straight-jeans-000LO0004_7_LD_FV_fbc43cf1-7445-46b6-a087-022e4b20b381_3558X2000.progressive.jpg?v=1750403974", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 23,
    name: "Puma Womens Tshirt",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "PUMA",
gender: "WOMEN",
category: "CASUAL", 
size: [38, 40, 42, 44],
color: ["white", "Blue", "Red"],
price: 1199,
discountPrice : 899,
is_in_inventory: true,
items_left: 8,
imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHpZIPJ8VEUhptxgD-A9LSviPlWhiMskLDWA&s", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 24,
    name: "Park Avenue Signature Collection",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "PARK AVENUE",
gender: "MEN",
category: "PARTY", 
size: [100, 150, 200],
color: ["Discover", "Voyage", "Neo"],
price: 499,
discountPrice : 359,
is_in_inventory: true,
items_left: 6,
imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6yLMOiRCIcvFb6jFUdrMA5L9blvcaxQCQ9g&s", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 25,
    name: "Santoor Soap",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "SANTOOR",
gender: "MEN",
category: "SOAP", 
size: [30, 50, 100, 125],
color: ["white", "Pink", "Orange"],
price: 159,
discountPrice : 129,
is_in_inventory: false,
items_left: 0,
imageURL: "https://tiimg.tistatic.com/fp/1/007/805/soft-smooth-skin-friendly-long-lasting-nourishment-santoor-white-soap--291.jpg", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 26,
    name: "Water Bottle Milton",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "MILTON",
gender: "MEN",
category: "CASUAL", 
size: [500, 600, 750, 1000],
color: ["Red", "Olive", "Black"],
price: 1029,
discountPrice : 759,
is_in_inventory: true,
items_left: 3,
imageURL: "https://media.istockphoto.com/id/1423379549/vector/blank-metal-insulated-water-bottle-vector-mockup-reusable-stainless-steel-travel-sport-flask.jpg?s=612x612&w=0&k=20&c=mXeJNB9xF7jh2Q8mGxkuenoyhEcgxdaBx9BaffVDb6k=", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 27,
    name: " Lunch Box On White",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "ISTOCK",
gender: "MEN",
category: "CASUAL", 
size: [500, 750],
color: ["Green", "Blue", "Black"],
price: 1039,
discountPrice : 869,
is_in_inventory: false,
items_left: 3,
imageURL: "https://media.istockphoto.com/id/1275872927/photo/healthy-school-lunch-lunch-time.jpg?s=612x612&w=0&k=20&c=iaX8fqe0HsX8G18-hstwGgBlFDkZvEIOzkNg-xs0MD4=", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 28,
    name: "Girls Dress Kids",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "ITAMY",
gender: "KIDS",
category: "CASUAL", 
size: [40, 42, 44, 46],
color: ["white", "Gray", "Pink"],
price: 1949,
discountPrice : 1299,
is_in_inventory: true,
items_left: 3,
imageURL: "https://itsmycostume.com/wp-content/uploads/4-28.jpg", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 29,
    name: "Men's Adidas Precision",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "ADIDAS",
gender: "MEN",
category: "CASUAL", 
size: [6, 7, 8, 9, 10],
color: ["white", "Blue", "Black"],
price: 1499,
discountPrice : 959,
is_in_inventory: false,
items_left: 0,
imageURL: "https://img.tatacliq.com/images/i22//437Wx649H/MP000000025623006_437Wx649H_202503090456561.jpeg", 
slug: "nike-react-infinity-run-flyknit"
  },
  {
    id: 30,
    name: "Puma Vapor Pro 3",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
brand: "PUMA",
gender: "MEN",
category: "SNEAKER", 
size: [6, 7, 8, 9, 10],
color: ["Orange", "Green", "Black"],
price: 1699,
discountPrice : 1239,
is_in_inventory: true,
items_left: 3,
imageURL: "https://images-cdn.ubuy.co.in/634d06b811e5df5c442cfe99-192799-01-mens-puma-hybrid-astro.jpg", 
slug: "nike-react-infinity-run-flyknit"
  },
];
 
  totalProductsCount = this.products.length;
  productInStock = this.products.filter(p => p.is_in_inventory).length;
  productOutOfStock = this.products.filter(p => !p.is_in_inventory).length;

  onFilterChanged(value: string) {
    this.selectedFilterRadioButton = value;
  }

  viewProduct(product: Product) {
    this.productSelected.emit(product);
  }

  get filteredProducts(): Product[] {
    return this.products.filter(prod => {
      const matchSearch =
        this.searchText === '' || prod.name.toLowerCase().includes(this.searchText.toLowerCase());
      const matchFilter =
        this.selectedFilterRadioButton === 'all' ||
        (this.selectedFilterRadioButton === 'inStock' && prod.is_in_inventory) ||
        (this.selectedFilterRadioButton === 'outOfStock' && !prod.is_in_inventory);

      return matchSearch && matchFilter;
    });
  }
}
